### register
POST http://localhost:8080/api/session/register
Content-Type: application/json

{
    "firtsName": "pablo",
    "lastName": "maguirre",
    "email": "maguirrepablo@hotmail.comm",
    "userName": "macpabloo",
    "birthDate": "1996-08-15",
    "password": "macpabli"
}

### register
POST http://localhost:8080/api/session/register
Content-Type: application/json

{
    "firtsName": "alan",
    "lastName": "maguirre",
    "email": "macguirre@hotmail.com",
    "userName": "macalan",
    "birthDate": "1996-08-15",
    "password": "macalan"
}

### register
POST http://localhost:8080/api/session/register
Content-Type: application/json

{
    "firtsName": "osvaldo",
    "lastName": "aguiar",
    "email": "osvaldooaguiar@hotmail.com",
    "userName": "valiaguiar",
    "birthDate": "1965-10-05",
    "password": "valiana"
}

### login
post http://localhost:8080/api/session/login
Content-Type: application/json

{
    "email": "andres22aguiar@gmail.com",
    "password": "andres"
}

### login
post http://localhost:8080/api/session/login
Content-Type: application/json

{
    "email": "osvaldooaguiar@hotmail.com",
    "password": "valiana"
}

### login
post http://localhost:8080/api/session/login
Content-Type: application/json

{
    "email": "adminCoder@coder.com",
    "password": "adminCod3r123"
}

### login
post http://localhost:8080/api/session/recover-password

### acceder al current
GET http://localhost:8080/api/session/current

### privada
GET http://localhost:8080/api/session/privada

### logout
GET http://localhost:8080/api/session/logout

